development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: ericisaac_development
  username: postgres

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: ericisaac_test
  username: postgres

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: ericisaac
  username: postgres
